version: "3.1"

services:
  audio_hunter_bot:
    container_name: audio_hunter_bot
    environment:
      BOT_TOKEN: "your_bot_token"
      BOT_ADMIN_USER_ID: "your_user_id"
      SEARCH_RESULT_COUNT: "5"
      DATABASE_PATH: "data/sounds_database.db"
      TOP_USER_REQUESTS_COUNT: "5"
      FEEDBACK_MESSAGE: "Сообщение для обратной связи"
      WEBAPP_URL: "https://example.com"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"